version: '3.3'

services:
  api:
    build: .
    command: npm run watch
    environment:
      - NODE_ENV=development
    ports:
      - '4000:4000'
    working_dir: /usr/app
    volumes:
      - '.:/usr/app'
